---
abstract: 'Log messages to separate files in a directory, with rotate options'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Probe::Perl: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Dispatch-Dir
requires:
  File::Slurp: 0
  Log::Dispatch::Output: 0
  Params::Validate: 0
  Taint::Util: 0
  perl: 5.010001
resources:
  homepage: http://search.cpan.org/dist/Log-Dispatch-Dir/
  repository: http://github.com/sharyanto/perl-Log-Dispatch-Dir
version: 0.11
