---
abstract: 'Log messages to separate files in a directory, with rotate options'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200007, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Dispatch-Dir
requires:
  File::Slurp: 0
  Log::Dispatch: 0
  POSIX: 0
  Params::Validate: 0
  Taint::Util: 0
  perl: 5.010000
resources:
  homepage: http://search.cpan.org/dist/Log-Dispatch-Dir/
  repository: http://github.com/sharyanto/perl-Log-Dispatch-Dir
version: 0.09
